name: Deploy TruePortMe Backend
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install and build
        run: |
          npm ci
          npm run build || true

      - name: Deploy files to EC2
        uses: burnett01/rsync-deployments@v3.1
        with:
          switches: -avz --delete
          path: "./"
          remote_path: "/var/www/trueportme-backend"
          remote_host: ${{ secrets.EC2_HOST }}
          remote_user: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

      - name: Create .env and restart backend
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/trueportme-backend
            echo "${{ secrets.PROD_ENV_FILE }}" > .env
            npm ci --omit=dev
            pm2 restart trueportme-backend --update-env || pm2 start src/server.js --name trueportme-backend --cwd /var/www/trueportme-backend
